### ISSUE TITLE
no movement and the robot does not move

### ISSUE THREAD

**Issue by wanjiaqi7** [OscarHuangWind/DRL-Transformer-SimtoReal-Navigation#11]
After running main.py, as shown in the picture, there is no movement and the robot does not move. Is this correct?
![P@6V%CX}DAPOPYF`GTE0(CX](https://github.com/OscarHuangWind/DRL-Transformer-SimtoReal-Navigation/assets/135974821/efbead8e-dc2a-4b22-b456-22387057ddde)

**Comment by OscarHuangWind** [comment]
From the screenshot I did not see any issues. Can you provide more details regarding following two points:
1. Is the code from line 429 to 432 in main.py file commented out? It should be commented out if you run the program through the terminal, otherwise the plot will block the thread.
2. Does it show any error when you launch the code?
